baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Amit Kumar"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-188161444-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Taxonomies]
    tag = "test"

[params]
#googleAnalytics = "UA-188161444-1"
googleMeasurementID = "G-MCH569NNFG"
html_title = "Amit Kumar | PhD Fin. | HKUST"
author = "Amit Kumar"
copyright = ""
meta_description = "Amit Kumar is a PhD student in Finance at HKUST. His research interest includes household finance, municipal finance, and banking."
sidebar_title = "Amit Kumar"
sidebar_line1 = "PhD Candidate in Finance at HKUST."
sidebar_line2 = "Room 5067. LSK, HKUST. Clear Water Bay. Hong Kong SAR."
sidebar_line3 = "amit.kumar@connect.ust.hk"
profilePicture = "images/1.jpg"
profilePicture_alt = "Amit Kumar, PhD Finance, HKUST" 
ssrn_email = "https://papers.ssrn.com/sol3/GetAuthorEmail.cfm?partid=2664500"
url_cv = "files/Amit_CV.pdf"
url_ssrn = "https://www.ssrn.com/author=2664500"
keywords = "Amit Kumar HKUST, Amit Kumar PhD Finance"
favicon = "images/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = []
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"


disableThemeSwitcher = true
disableKinds = ["section", "taxonomy", "taxonomyTerm"] #Disable all sections, we have single page layout
[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"


## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
#[[params.socialIcons]]
#icon = "fab fa-linkedin"
#title = "Linkedin"
#url = "https://www.linkedin.com/in/amit-kumar-phd-finance/"

#[[params.socialIcons]]
#icon = "fab fa-instagram"
#title = "SSRN"
#url = "www.ssrn.com/author=2664500"

[[params.socialIcons]]
#icon = "fas fa-envelope"
#title = "e-mail"
#url = "mailto:akumarac@connect.ust.hk"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
  title= "Amit Kumar, PhD Finance, HKUST" #title for menu items

[sitemap]
 changefreq = "weekly"
 filename = "sitemap.xml"
 priority = 1
  

[frontmatter]
lastmod = [":fileModTime", ":default"] #This sets last modification date to modification date of content file.